#!/bin/bash

########################
########################
#Author: Anna Maria Langmüller 
#Year: 2020
#Department: Vetmed University Vienna, Department of Population Genetics
#Project: Low concordance of short-term and long-term selection responses in experimental Drosophila populations
#Purpose: Calculate CMH tests for simulated data

#####################
#####################
cd ../data_sim

perl ../src_sim/popoolation2/cmh-test.pl --input DsimFl_20200109-SNPSet01_hemizygousX-ds80x_F0F10-ordered_CovSampled.sync --output DsimFl_20200109-SNPSet01_hemizygousX-ds80x_F0F10-ordered_CovSampled.sync.cmh --min-count 10 --min-coverage 1 --max-coverage 1000 --population 1-11,2-12,3-13,4-14,5-15,6-16,7-17,8-18,9-19,10-20 --remove-temp

perl ../src_sim/popoolation2/cmh-test.pl --input DsimFl_20200109-SNPSet01_hemizygousX-ds80x_F0F20-ordered_CovSampled.sync --output DsimFl_20200109-SNPSet01_hemizygousX-ds80x_F0F20-ordered_CovSampled.sync.cmh --min-count 10 --min-coverage 1 --max-coverage 1000 --population 1-11,2-12,3-13,4-14,5-15,6-16,7-17,8-18,9-19,10-20 --remove-temp

perl ../src_sim/popoolation2/cmh-test.pl --input DsimFl_20200109-SNPSet01_hemizygousX-ds80x_F0F30-ordered_CovSampled.sync --output DsimFl_20200109-SNPSet01_hemizygousX-ds80x_F0F30-ordered_CovSampled.sync.cmh --min-count 10 --min-coverage 1 --max-coverage 1000 --population 1-11,2-12,3-13,4-14,5-15,6-16,7-17,8-18,9-19,10-20 --remove-temp

perl ../src_sim/popoolation2/cmh-test.pl --input DsimFl_20200109-SNPSet01_hemizygousX-ds80x_F0F40-ordered_CovSampled.sync --output DsimFl_20200109-SNPSet01_hemizygousX-ds80x_F0F40-ordered_CovSampled.sync.cmh --min-count 10 --min-coverage 1 --max-coverage 1000 --population 1-11,2-12,3-13,4-14,5-15,6-16,7-17,8-18,9-19,10-20 --remove-temp

perl ../src_sim/popoolation2/cmh-test.pl --input DsimFl_20200109-SNPSet01_hemizygousX-ds80x_F0F50-ordered_CovSampled.sync --output DsimFl_20200109-SNPSet01_hemizygousX-ds80x_F0F50-ordered_CovSampled.sync.cmh --min-count 10 --min-coverage 1 --max-coverage 1000 --population 1-11,2-12,3-13,4-14,5-15,6-16,7-17,8-18,9-19,10-20 --remove-temp

perl ../src_sim/popoolation2/cmh-test.pl --input DsimFl_20200109-SNPSet01_hemizygousX-ds80x_F0F60-ordered_CovSampled.sync --output DsimFl_20200109-SNPSet01_hemizygousX-ds80x_F0F60-ordered_CovSampled.sync.cmh --min-count 10 --min-coverage 1 --max-coverage 1000 --population 1-11,2-12,3-13,4-14,5-15,6-16,7-17,8-18,9-19,10-20 --remove-temp
